baseurl = "https://fenestro.xyz"
languageCode = "en-us"
title = "Fenestro: cli->html window"
description = "A simple Mac app to render HTML from the command line"

[params]
author = "masukomi"

[permalinks]
post = "/:year/:month/:title/"
